default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: minutu-api_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: minutu-api_test

production:
  <<: *default
  database: minutu-api_production
  username: minutu-api
  password: <%= ENV['MINUTU-API_DATABASE_PASSWORD'] %>
